"""Verdict labels — enum-like constants for all possible verdicts."""

TRUE = "TRUE"
MOSTLY_TRUE = "MOSTLY_TRUE"
MISLEADING = "MISLEADING"
FALSE = "FALSE"
UNVERIFIED = "UNVERIFIED"
NEEDS_CONTEXT = "NEEDS_CONTEXT"
NEEDS_MANUAL_VERIFICATION = "NEEDS_MANUAL_VERIFICATION"
SATIRE = "SATIRE"

ALL_LABELS = [
    TRUE, MOSTLY_TRUE, MISLEADING, FALSE,
    UNVERIFIED, NEEDS_CONTEXT, NEEDS_MANUAL_VERIFICATION, SATIRE,
]
