"""Disclaimer — mandatory AI disclosure appended to every response."""


DISCLAIMER = (
    "This analysis was generated by an AI system and may contain errors. "
    "Always verify claims using primary sources and independent research."
)


def append(text: str) -> str:
    """Ensure disclaimer is at end of text."""
    if DISCLAIMER not in text:
        text += f"\n\n{DISCLAIMER}"
    return text
