"""Output formatter — renders structured report from verdict data."""


def format_report(verdict: dict, sources: list, contradictions: list) -> str:
    """Render final markdown report. Template-driven, LLM does not control format."""
    lines = [
        f"# Verdict: {verdict.get('verdict', 'UNVERIFIED')}\n",
        f"**Confidence:** {verdict.get('confidence', 0.0)}\n",
        "",
        "## Summary",
        verdict.get("rationale", "No analysis available."),
        "",
        "## Evidence Chain",
        "*(Stub — evidence chain not yet implemented)*",
        "",
        "## AI Disclaimer",
        "This analysis was generated by an AI system and may contain errors. Always verify claims independently.",
    ]
    return "\n".join(lines)
